### ISSUE TITLE
OMP: Error #15

### ISSUE THREAD

**Issue by OlympicAngel** [Softcatala/whisper-ctranslate2#101]
While attempting to run it im getting error:

`OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.`

i have no idead what libiomp5md.dll or OpenMP, failed to get any data that i actully can understand..
my run command is:

`whisper-ctranslate2 "sample.mp3" --language he --output_format srt --output_dir "./audio/srv/" --verbose False --beam_size 5 --word_timestamps True --max_line_width 1 --max_line_count 1 --vad_filter True --vad_max_speech_duration_s 1 --vad_threshold 0.1 --suppress_blank False`

sample.mp3 is a 365kb file - i used previously with whisper-ctranslate2, no problem with that - its also happning with anyother file.
i have tried to uninstall/install - didnt help.

i did tried to install insanely-fast-whisper, but i didnt liked it so i deleted it..

any help will do!

**Comment by avc1657** [comment]
Hi, did you manage to fix the issue? I have the exact same issue going on my end.

**Comment by NBNGaming** [comment]
Same issue

**Comment by ChrisProkop** [comment]
Same issue for me.    Seems totally unresolvable even after making an entirely new Conda install.

**Comment by misters2008** [comment]
Search for libiomp5md.dll in a File Explorer and try to delete folders, where it is located.
I solved this issue taking this approach. 
However, it was a week ago and i already forgot all the little details, which might have been.
But the idea is if it is already initialized somewhere, need to find its location and remove it, so there is no more a source of its ghost initialization.
