### ISSUE TITLE
Problem after upgrading to 0.4.6

### ISSUE THREAD

**Issue by toboil-features** [Softcatala/whisper-ctranslate2#108]
whisper-ctranslate2 --help

Intel MKL FATAL ERROR: Cannot load /home/user/.local/share/pipx/venvs/whisper-ctranslate2/lib/python3.12/site-packages/ctranslate2/../ctranslate2.libs/libctranslate2-d3638643.so.4.4.0.

package whisper-ctranslate2 0.4.6, installed using Python 3.12.7
    - whisper-ctranslate2

**Comment by jordimas** [comment]
This looks like a Intel MKL Installation problem in your setup

You can also try with CT2_USE_MKL environment variable 
See: https://opennmt.net/CTranslate2/environment_variables.html?highlight=intel#ct2-use-mkl)

**Comment by toboil-features** [comment]
CT2_USE_MKL=0 environment variable resolved my problem.
