### ISSUE TITLE
"--task translate" is useless while using large-v3-turbo

### ISSUE THREAD

**Issue by toboil-features** [Softcatala/whisper-ctranslate2#109]
It makes program to make output slightly accurate, but not translated.
Spanish and other speeches in the audio are detected properly.

whisper-ctranslate2 /home/user/untitled.mp3 --device cpu --model=large-v3-turbo --task translate

By default, "translate" should translate all speech to English, but it doesn't.

**Comment by jordimas** [comment]
Keep in mind than the distil-large-* and large-v3-turbo* are recent or experimental models

Try large-v3, it should work.

**Comment by toboil-features** [comment]
I mean, the issue is still present as of 0.5.0
