### ISSUE TITLE
TypeError: WhisperModel.transcribe() got an unexpected keyword argument 'hotwords'?

### ISSUE THREAD

**Issue by silvacarl2** [Softcatala/whisper-ctranslate2#111]
got this strange error today, any ideas?

 time whisper-ctranslate2 --model large-v3-turbo --output_format txt --initial_prompt "bupren
orphine hydroxyzine naloxone triamcinolone venlafaxine" 21514473.mp3
Detecting language using up to the first 30 seconds. Use `--language` to specify the language
config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.26k/2.26k [00:00<00:00, 17.1MB/s]
tokenizer.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.71M/2.71M [00:00<00:00, 12.2MB/s]
Error: Unable to process file: 21514473.mp3
Exception Type: TypeError
Exception Message: WhisperModel.transcribe() got an unexpected keyword argument 'hotwords'
Traceback:
Traceback (most recent call last):
  File "/home/silvacarl/.local/lib/python3.10/site-packages/src/whisper_ctranslate2/whisper_ctranslate2.py", line 242, in main
    result = transcribe.inference(
  File "/home/silvacarl/.local/lib/python3.10/site-packages/src/whisper_ctranslate2/transcribe.py", line 132, in inference
    segments, info = self.model.transcribe(
TypeError: WhisperModel.transcribe() got an unexpected keyword argument 'hotwords'

**Comment by jordimas** [comment]
Please make sure that you have faster-whisper==1.02 or new installer

I will fix this

**Comment by silvacarl2** [comment]
yup fixed!
