### ISSUE TITLE
Error When Using vad_threshold Parameter: Unexpected Keyword Argument in VadOptions

### ISSUE THREAD

**Issue by RxChi1d** [Softcatala/whisper-ctranslate2#113]
First of all, thank you to the author for this excellent tool! It has been incredibly helpful for my task of transcribing meeting videos into text.

Recently, I encountered an issue when using the “vad_filter” option and setting the “vad_threshold” parameter while running the tool in Colab.

Here is the command I used:

```
!whisper-ctranslate2 temp.mkv \
  --output_format srt \
  --language {language} \
  --model {model_size} \
  --word_timestamps True \
  --condition_on_previous_text False \
  --temperature 0.5 \
  --temperature_increment_on_fallback 0.3 \
  --repetition_penalty 1.2 \
  --no_repeat_ngram_size 3 \
  --logprob_threshold -1.5 \
  --hallucination_silence_threshold 2 \
  --vad_filter True \
  --vad_threshold 0.3 \
  --length_penalty 0.8 \
  --initial_prompt {init_prompt}
```

However, when I remove the “vad_threshold” parameter, the process works fine.

Here’s how I installed the packages:

```
!pip install -U whisper-ctranslate2
!pip install ctranslate2==4.4.0
```

When using the “vad_threshold” parameter, the following error occurs:

```
Error: Unable to process file: temp.mkv
Exception Type: TypeError
Exception Message: VadOptions.__init__() got an unexpected keyword argument 'threshold'
Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/src/whisper_ctranslate2/whisper_ctranslate2.py", line 241, in main
    result = transcribe.inference(
  File "/usr/local/lib/python3.10/dist-packages/src/whisper_ctranslate2/transcribe.py", line 144, in inference
    segments, info = model.transcribe(
  File "/usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py", line 834, in transcribe
    vad_parameters = VadOptions(**vad_parameters)
TypeError: VadOptions.__init__() got an unexpected keyword argument 'threshold'

Transcription results written to '/content' directory
```

It seems that the VadOptions class does not accept the threshold parameter. Could you please help me understand what might be causing this issue and how to resolve it?

Thank you so much for your support!

**Comment by jordimas** [comment]
Yes, this is due to a change of name in faster-whisper.

If you install version whisper-ctranslate2 0.49 this should be fixed. The old "--vad_threshold" is now  "--vad_onset" to reflect the change in faster-whisper.

**Comment by RxChi1d** [comment]
thanks for fixing this problem, and your pretty good work~~!

**Comment by RxChi1d** [comment]
thanks for fixing this problem, and your pretty good work~~!
