### ISSUE TITLE
Error with Japanese subtitles

### ISSUE THREAD

**Issue by rsmith02ct** [Softcatala/whisper-ctranslate2#15]
I'm attempting to generate text for Japanese audio through SubtitleEdit but getting this error which appears to be a python issue with the characters:

Date: 04/14/2023 13:57:40
SE: 3.6.12.62 - Microsoft Windows NT 10.0.22621.0 - 64-bit
Message: Calling whisper (CTranslate2) with : C:\Users\rsmit\Dropbox\transfer settings\Whisper-Faster\Whisper-Faster\whisper-ctranslate2.exe --language ja --model "large"  "D:\Temp\3787e9c7-46dd-4055-aa58-377ada7b89e0.wav"
UnicodeEncodeError: 'charmap' codec can't encode characters in position 26-45: character maps to <undefined>

File "encodings\cp1252.py", line 19, in encode

File "D:\whisper-fast\__main__.py", line 399, in cli

File "D:\whisper-fast\__main__.py", line 406, in <module>

Traceback (most recent call last):

[3696] Failed to execute script '__main__' due to unhandled exception!

Calling whisper CTranslate2 done in 00:00:09.1675218
Loading result from STDOUT

**Comment by jordimas** [comment]
Thanks for reporting this.

Do you have more details of the errors? Can you share if more things are displayed? (e.g. Traceback (most recent call last):)

Does the problem appear if you execute the application with the parameter "--verbose False"?

Finally, will be possible to share a file that allows me to reproduce the problem?

Thanks

**Comment by rsmith02ct** [comment]
Hi Jordi,
I'm happy to do more testing but need a little bit of help.

There's been some discussion here on this topic:
https://github.com/SubtitleEdit/subtitleedit/issues/6816#issuecomment-1507934536


As I am going through SubtitleEdit I am not sure how to pass through
additional parameters.
Do you have a sample command line template I could use? For Whisper I was
using: whisper.exe --device cuda --language ja --model "base"
"C:\Users\rsmit\Dropbox\Videos\10 MPantry final new titles 2.mp4"

This is the file I've been testing (already public video with Japanese
narration):
https://www.dropbox.com/s/3gjxcubx7axftgk/10%20MPantry%20final%20new%20titles%202.mp4?dl=0
Really though any audio file should work as Whisper doesn't know what
language it is and will attempt to find Japanese if you tell it the source
is Japanese.

This is all the SubtitleEdit Error_log had for this:

-----------------------------------------------------------------------------
Date: 04/14/2023 15:38:13
SE: 3.6.12.62 - Microsoft Windows NT 10.0.22621.0 - 64-bit
Message: C:\Users\rsmit\Dropbox\transfer
settings\Whisper-Faster\Whisper-Faster\whisper-ctranslate2.exe --language
ja --model "base"  "D:\Temp\dbd53e23-f07c-4f50-9385-a72d2514d600.wav"

-----------------------------------------------------------------------------
Date: 04/14/2023 15:38:17
SE: 3.6.12.62 - Microsoft Windows NT 10.0.22621.0 - 64-bit
Message: Calling whisper (CTranslate2) with :
C:\Users\rsmit\Dropbox\transfer
settings\Whisper-Faster\Whisper-Faster\whisper-ctranslate2.exe --language
ja --model "base"  "D:\Temp\dbd53e23-f07c-4f50-9385-a72d2514d600.wav"
UnicodeEncodeError: 'charmap' codec can't encode characters in position
26-216: character maps to <undefined>

File "encodings\cp1252.py", line 19, in encode

File "D:\whisper-fast\__main__.py", line 399, in cli

File "D:\whisper-fast\__main__.py", line 406, in <module>

Traceback (most recent call last):

[17000] Failed to execute script '__main__' due to unhandled exception!
Calling whisper CTranslate2 done in 00:00:03.3541655
Loading result from STDOUT

**Comment by jordimas** [comment]
Try with --device cuda --language ja --model "base" --verbose False

To see if makes any difference. Thanks

**Comment by rsmith02ct** [comment]
Thanks for that.

So here's the full command line (ran cmd as admin): whisper-ctranslate2.exe
--device cuda --language ja --model "base" --verbose False
"C:\Users\rsmit\Dropbox\Videos\10 MPantry final new titles 2.mp4"

and here's the "output"- a few misheard characters repeated again and
again? I don't see any output srt file.

[image: image.png]

**Comment by jordimas** [comment]
Thanks

I cannot see the image that you shared.

My understading is that now it did finished but no contents on the files. Correct?

**Comment by rsmith02ct** [comment]
![Screenshot 2023-04-14 16 35 47](https://user-images.githubusercontent.com/122251109/231982574-b5a48fb4-666d-4094-bbb6-fde580009356.png)
Sorry about that, though I could just do it from email. 

It just gave a few repeated garbage characters and no file that I could find (nothing in the source footage folder or Faster Whisper folder).

**Comment by jordimas** [comment]
Thanks, let me have a a look in the next days and come back to you.

**Comment by rsmith02ct** [comment]
I appreciate it and and am happy to perform more tests to isolate the issue.

**Comment by jordimas** [comment]
I did a test in Windows an it works for me:

<img width="1008" alt="Captura de pantalla 2023-04-14 a les 15 31 13" src="https://user-images.githubusercontent.com/309265/232057553-b813c545-f528-4ab6-b6be-c8e2d30cd032.png">

Can you check which version of whisper-ctranslate2 are you running? Just type whisper-ctranslate2 --version

**Comment by rsmith02ct** [comment]
Hmm, while the quality of this transcription is much lower than I've seen
with Whisper using a base model (mostly nonsensical with bits of cyrillic
and English thrown in) not sure why it "works" for you but not for me and
the other poster in SubtitleEdit.

Purfview is where I got the compiled build from:
https://github.com/Purfview/whisper-standalone-win/releases/tag/v2023.03.31-b77-faster

Version gave an error:
D:\My Documents\Dropbox\transfer
settings\Whisper-Faster\Whisper-Faster>whisper-ctranslate2 --version
usage: whisper-ctranslate2 [-h] [--model
{tiny,tiny.en,base,base.en,small,small.en,medium,medium.en,large}]
[--model_dir MODEL_DIR] [--device DEVICE] [--output_dir OUTPUT_DIR]
[--output_format {txt,vtt,srt,tsv,json,all}]
                           [--verbose VERBOSE] [--task
{transcribe,translate}]
                           [--language
{af,am,ar,as,az,ba,be,bg,bn,bo,br,bs,ca,cs,cy,da,de,el,en,es,et,eu,fa,fi,fo,fr,gl,gu,ha,haw,he,hi,hr,ht,hu,hy,id,is,it,ja,jw,ka,kk,km,kn,ko,la,lb,ln,lo,lt,lv,mg,mi,mk,ml,mn,mr,ms,mt,my,ne,nl,nn,no,oc,pa,pl,ps,pt,ro,ru,sa,sd,si,sk,sl,sn,so,sq,sr,su,sv,sw,ta,te,tg,th,tk,tl,tr,tt,uk,ur,uz,vi,yi,yo,zh,Afrikaans,Albanian,Amharic,Arabic,Armenian,Assamese,Azerbaijani,Bashkir,Basque,Belarusian,Bengali,Bosnian,Breton,Bulgarian,Burmese,Castilian,Catalan,Chinese,Croatian,Czech,Danish,Dutch,English,Estonian,Faroese,Finnish,Flemish,French,Galician,Georgian,German,Greek,Gujarati,Haitian,Haitian
Creole,Hausa,Hawaiian,Hebrew,Hindi,Hungarian,Icelandic,Indonesian,Italian,Japanese,Javanese,Kannada,Kazakh,Khmer,Korean,Lao,Latin,Latvian,Letzeburgesch,Lingala,Lithuanian,Luxembourgish,Macedonian,Malagasy,Malay,Malayalam,Maltese,Maori,Marathi,Moldavian,Moldovan,Mongolian,Myanmar,Nepali,Norwegian,Nynorsk,Occitan,Panjabi,Pashto,Persian,Polish,Portuguese,Punjabi,Pushto,Romanian,Russian,Sanskrit,Serbian,Shona,Sindhi,Sinhala,Sinhalese,Slovak,Slovenian,Somali,Spanish,Sundanese,Swahili,Swedish,Tagalog,Tajik,Tamil,Tatar,Telugu,Thai,Tibetan,Turkish,Turkmen,Ukrainian,Urdu,Uzbek,Valencian,Vietnamese,Welsh,Yiddish,Yoruba}]
                           [--temperature TEMPERATURE] [--best_of BEST_OF]
[--beam_size BEAM_SIZE] [--patience PATIENCE] [--length_penalty
LENGTH_PENALTY] [--suppress_tokens SUPPRESS_TOKENS] [--initial_prompt
INITIAL_PROMPT]
                           [--condition_on_previous_text
CONDITION_ON_PREVIOUS_TEXT] [--fp16 FP16]
[--temperature_increment_on_fallback TEMPERATURE_INCREMENT_ON_FALLBACK]
                           [--compression_ratio_threshold
COMPRESSION_RATIO_THRESHOLD] [--logprob_threshold LOGPROB_THRESHOLD]
[--no_speech_threshold NO_SPEECH_THRESHOLD] [--word_timestamps
WORD_TIMESTAMPS]
                           [--prepend_punctuations PREPEND_PUNCTUATIONS]
[--append_punctuations APPEND_PUNCTUATIONS] [--threads THREADS]
                           audio [audio ...]
whisper-ctranslate2: error: the following arguments are required: audio

**Comment by jordimas** [comment]
You are not executing whisper-ctranslate2, you are really executing OpenAI whisper client. I guess that you renamed the binary or similar.

As you can see below whisper-ctranslate2 has more options that you are showing. You are not running whisper-ctranslate2 


_usage: whisper-ctranslate2 [-h] [--model {tiny,tiny.en,base,base.en,small,small.en,medium,medium.en,large-v1,large-v2}] [--model_dir MODEL_DIR] [--output_dir OUTPUT_DIR]
                           [--output_format {txt,vtt,srt,tsv,json,all}] [--verbose VERBOSE] [--task {transcribe,translate}]
                           [--language {af,am,ar,as,az,ba,be,bg,bn,bo,br,bs,ca,cs,cy,da,de,el,en,es,et,eu,fa,fi,fo,fr,gl,gu,ha,haw,he,hi,hr,ht,hu,hy,id,is,it,ja,jw,ka,kk,km,kn,ko,la,lb,ln,lo,lt,lv,mg,mi,mk,ml,mn,mr,ms,mt,my,ne,nl,nn,no,oc,pa,pl,ps,pt,ro,ru,sa,sd,si,sk,sl,sn,so,sq,sr,su,sv,sw,ta,te,tg,th,tk,tl,tr,tt,uk,ur,uz,vi,yi,yo,zh,Afrikaans,Albanian,Amharic,Arabic,Armenian,Assamese,Azerbaijani,Bashkir,Basque,Belarusian,Bengali,Bosnian,Breton,Bulgarian,Burmese,Castilian,Catalan,Chinese,Croatian,Czech,Danish,Dutch,English,Estonian,Faroese,Finnish,Flemish,French,Galician,Georgian,German,Greek,Gujarati,Haitian,Haitian Creole,Hausa,Hawaiian,Hebrew,Hindi,Hungarian,Icelandic,Indonesian,Italian,Japanese,Javanese,Kannada,Kazakh,Khmer,Korean,Lao,Latin,Latvian,Letzeburgesch,Lingala,Lithuanian,Luxembourgish,Macedonian,Malagasy,Malay,Malayalam,Maltese,Maori,Marathi,Moldavian,Moldovan,Mongolian,Myanmar,Nepali,Norwegian,Nynorsk,Occitan,Panjabi,Pashto,Persian,Polish,Portuguese,Punjabi,Pushto,Romanian,Russian,Sanskrit,Serbian,Shona,Sindhi,Sinhala,Sinhalese,Slovak,Slovenian,Somali,Spanish,Sundanese,Swahili,Swedish,Tagalog,Tajik,Tamil,Tatar,Telugu,Thai,Tibetan,Turkish,Turkmen,Ukrainian,Urdu,Uzbek,Valencian,Vietnamese,Welsh,Yiddish,Yoruba}]
                           [--threads THREADS] [--temperature TEMPERATURE] [--temperature_increment_on_fallback TEMPERATURE_INCREMENT_ON_FALLBACK] [--best_of BEST_OF]
                           [--beam_size BEAM_SIZE] [--patience PATIENCE] [--length_penalty LENGTH_PENALTY] [--suppress_tokens SUPPRESS_TOKENS] [--initial_prompt INITIAL_PROMPT]
                           [--condition_on_previous_text CONDITION_ON_PREVIOUS_TEXT] [--compression_ratio_threshold COMPRESSION_RATIO_THRESHOLD]
                           [--logprob_threshold LOGPROB_THRESHOLD] [--no_speech_threshold NO_SPEECH_THRESHOLD] [--word_timestamps WORD_TIMESTAMPS]
                           [--prepend_punctuations PREPEND_PUNCTUATIONS] [--append_punctuations APPEND_PUNCTUATIONS] [--device DEVICE] [--vad_filter VAD_FILTER]
                           [--vad_min_silence_duration_ms VAD_MIN_SILENCE_DURATION_MS] [--device_index [DEVICE_INDEX ...]]
                           [--compute_type {default,auto,int8,int8_float16,int16,float16,float32}] [--model_directory MODEL_DIRECTORY] [--print_colors PRINT_COLORS] [--version]
                           [--live_transcribe LIVE_TRANSCRIBE]
                           [audio ...]

positional arguments:
  audio                 audio file(s) to transcribe (default: None)

options:
  -h, --help            show this help message and exit
  --model {tiny,tiny.en,base,base.en,small,small.en,medium,medium.en,large-v1,large-v2}
                        name of the Whisper model to use (default: small)
  --model_dir MODEL_DIR
                        the path to save model files; uses ~/.cache/whisper-ctranslate2 by default (default: None)
  --output_dir OUTPUT_DIR, -o OUTPUT_DIR
                        directory to save the outputs (default: .)
  --output_format {txt,vtt,srt,tsv,json,all}, -f {txt,vtt,srt,tsv,json,all}
                        format of the output file; if not specified, all available formats will be produced (default: all)
  --verbose VERBOSE     whether to print out the progress and debug messages (default: True)
  --task {transcribe,translate}
                        whether to perform X->X speech recognition ('transcribe') or X->English translation ('translate') (default: transcribe)
  --language {af,am,ar,as,az,ba,be,bg,bn,bo,br,bs,ca,cs,cy,da,de,el,en,es,et,eu,fa,fi,fo,fr,gl,gu,ha,haw,he,hi,hr,ht,hu,hy,id,is,it,ja,jw,ka,kk,km,kn,ko,la,lb,ln,lo,lt,lv,mg,mi,mk,ml,mn,mr,ms,mt,my,ne,nl,nn,no,oc,pa,pl,ps,pt,ro,ru,sa,sd,si,sk,sl,sn,so,sq,sr,su,sv,sw,ta,te,tg,th,tk,tl,tr,tt,uk,ur,uz,vi,yi,yo,zh,Afrikaans,Albanian,Amharic,Arabic,Armenian,Assamese,Azerbaijani,Bashkir,Basque,Belarusian,Bengali,Bosnian,Breton,Bulgarian,Burmese,Castilian,Catalan,Chinese,Croatian,Czech,Danish,Dutch,English,Estonian,Faroese,Finnish,Flemish,French,Galician,Georgian,German,Greek,Gujarati,Haitian,Haitian Creole,Hausa,Hawaiian,Hebrew,Hindi,Hungarian,Icelandic,Indonesian,Italian,Japanese,Javanese,Kannada,Kazakh,Khmer,Korean,Lao,Latin,Latvian,Letzeburgesch,Lingala,Lithuanian,Luxembourgish,Macedonian,Malagasy,Malay,Malayalam,Maltese,Maori,Marathi,Moldavian,Moldovan,Mongolian,Myanmar,Nepali,Norwegian,Nynorsk,Occitan,Panjabi,Pashto,Persian,Polish,Portuguese,Punjabi,Pushto,Romanian,Russian,Sanskrit,Serbian,Shona,Sindhi,Sinhala,Sinhalese,Slovak,Slovenian,Somali,Spanish,Sundanese,Swahili,Swedish,Tagalog,Tajik,Tamil,Tatar,Telugu,Thai,Tibetan,Turkish,Turkmen,Ukrainian,Urdu,Uzbek,Valencian,Vietnamese,Welsh,Yiddish,Yoruba}
                        language spoken in the audio, specify None to perform language detection (default: None)
  --threads THREADS     number of threads used for CPU inference (default: 0)
  --temperature TEMPERATURE
                        temperature to use for sampling (default: 0)
  --temperature_increment_on_fallback TEMPERATURE_INCREMENT_ON_FALLBACK
                        temperature to increase when falling back when the decoding fails to meet either of the thresholds below (default: 0.2)
  --best_of BEST_OF     number of candidates when sampling with non-zero temperature (default: 5)
  --beam_size BEAM_SIZE
                        number of beams in beam search, only applicable when temperature is zero (default: 5)
  --patience PATIENCE   optional patience value to use in beam decoding, as in https://arxiv.org/abs/2204.05424, the default (1.0) is equivalent to conventional beam search
                        (default: 1.0)
  --length_penalty LENGTH_PENALTY
                        optional token length penalty coefficient (alpha) as in https://arxiv.org/abs/1609.08144, uses simple length normalization by default (default: 1.0)
  --suppress_tokens SUPPRESS_TOKENS
                        comma-separated list of token ids to suppress during sampling; '-1' will suppress most special characters except common punctuations (default: -1)
  --initial_prompt INITIAL_PROMPT
                        optional text to provide as a prompt for the first window. (default: None)
  --condition_on_previous_text CONDITION_ON_PREVIOUS_TEXT
                        if True, provide the previous output of the model as a prompt for the next window; disabling may make the text inconsistent across windows, but the
                        model becomes less prone to getting stuck in a failure loop (default: True)
  --compression_ratio_threshold COMPRESSION_RATIO_THRESHOLD
                        if the gzip compression ratio is higher than this value, treat the decoding as failed (default: 2.4)
  --logprob_threshold LOGPROB_THRESHOLD
                        if the average log probability is lower than this value, treat the decoding as failed (default: -1.0)
  --no_speech_threshold NO_SPEECH_THRESHOLD
                        if the probability of the <|nospeech|> token is higher than this value AND the decoding has failed due to `logprob_threshold`, consider the segment as
                        silence (default: 0.6)
  --word_timestamps WORD_TIMESTAMPS
                        (experimental) extract word-level timestamps and refine the results based on them (default: False)
  --prepend_punctuations PREPEND_PUNCTUATIONS
                        if word_timestamps is True, merge these punctuation symbols with the next word (default: "'“¿([{-)
  --append_punctuations APPEND_PUNCTUATIONS
                        if word_timestamps is True, merge these punctuation symbols with the previous word (default: "'.。,，!！?？:：”)]}、)
  --device DEVICE       device to use for CTranslate2 inference (default: auto)
  --vad_filter VAD_FILTER
                        Enable the voice activity detection (VAD) to filter out parts of the audio without speech. This step is using the Silero VAD model
                        https://github.com/snakers4/silero-vad. (default: False)
  --vad_min_silence_duration_ms VAD_MIN_SILENCE_DURATION_MS
                        When `vad_filter` is enabled, audio segments without speech for at least this number of milliseconds will be ignored. (default: 2000)
  --device_index [DEVICE_INDEX ...]
                        Device IDs where to place this model on (default: 0)
  --compute_type {default,auto,int8,int8_float16,int16,float16,float32}
                        Type of quantization to use (see https://opennmt.net/CTranslate2/quantization.html) (default: auto)
  --model_directory MODEL_DIRECTORY
                        Directory where to find a CTranslate Whisper model (e.g. fine-tuned model) (default: None)
  --print_colors PRINT_COLORS
                        Print the transcribed text using an experimental color coding strategy to highlight words with high or low confidence (default: False)
  --version             Show program's version number and exit
  --live_transcribe LIVE_TRANSCRIBE
                        Live transcribe mode (default: False)_

**Comment by ras0k** [comment]
> Thank you for confirming that, I'll ask the person who made this binary what it is as I'm just a user trying to test implementations for Subtitle Edit.

maybe the user had malicious intent, faster-whisper is just a branding, the actual software you would interact with through CLI is called whisper-cTranslate2

**Comment by rsmith02ct** [comment]
Okay, I'm trying to do this properly and installed it from git.

whisper-ctranslate2 --version
whisper-ctranslate2 0.1.8

Is that a proper one?

**Comment by jordimas** [comment]
Yes, this is the last version. Great!

**Comment by Purfview** [comment]
OP meant that the standalone executables compiled with pyinstaller fails with that error on Japanese in SubtitleEdit.
When OP didn't used a compile from this repo, same "UnicodeEncodeError" error is produced with a compile from this repo too.

I'm pretty rusty on Python, need to read up why it happens.

**Comment by jordimas** [comment]
@Purfview  Some questions:
* Can you run whisper-ctranslate2 --version and report the version?
* What steps can I follow to setup whisper-ctranslate2 to work with SubtitleEdit as you guys are doing?

Thanks

**Comment by Purfview** [comment]
It reported `whisper 0.1.9`.

Get SE beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.12/SubtitleEditBeta.zip
Your repo compiled [CPU only]: [whisper-ctranslate2.exe](https://we.tl/t-kEL895k6wd)
Short Japanese sample: [test_ja.wav](https://we.tl/t-thzwi1ZsNM)

Then it's usual, SE will ask you to point to `whisper-ctranslate2.exe`, do Japanese transcription, see error output in SE's root in file `error_log.txt`.

**Comment by rsmith02ct** [comment]
For SubtitleEdit you need the current beta (standalone): https://github.com/SubtitleEdit/subtitleedit/releases 
Then go to video/audio to text Whisper. For engine select ctranslate2. Models should be in the default folder. Then just add a file and hit generate.

I think if it didn't default to CUDA it would likely work as is here.

**Comment by Purfview** [comment]
> I think if it didn't default to CUDA it would likely work as is here.

No, "CPU only" can't default to CUDA.

**Comment by rsmith02ct** [comment]
I'm using "whisper-ctranslate2 0.1.8" and from the command line with --device CPU it functions here.

**Comment by Purfview** [comment]
@rsmith02ct Maybe you are mixing the issues because in SE you can't set any commands.

**Comment by rsmith02ct** [comment]
SE must send commands to the CLI executable- how else is the model type set? (and probably output type and location?) We just can't control what it sends.

**Comment by Purfview** [comment]
In SE you can select only language, model and audio file, only those are sent as command.

**Comment by jordimas** [comment]
> Your repo compiled [CPU only]: [whisper-ctranslate2.exe](https://we.tl/t-kEL895k6wd)

I will suggest to install it using

pip install -U whisper-ctranslate2

If you can please open a separate bug report for your issue. We are mixing here different configurations what makes difficult to debug. Thanks

**Comment by Purfview** [comment]
I personally don't have issue as I don't use SE.
I'm not sure what other "configuration" you are trying to debug when my post is the only "configuration" related to the actual issue.

**Comment by Purfview** [comment]
> I will suggest to install it using:
> 
> pip install -U whisper-ctranslate2

I'm sure it would produce same error.

**Comment by keimaruO** [comment]
I'm also experiencing the same issue with Japanese subtitles. I've been using version 0.1.1 as a workaround. You might want to try this version too. Here's how to install it:


Uninstall command:
```
pip uninstall whisper-ctranslate2
```
Install version 0.1.1:
```
pip install git+https://github.com/jordimas/whisper-ctranslate2.git@0.1.1
```
I hope this helps!

**Comment by snowy5719** [comment]
Purfview
Please to install cuda sdk(v11).

**Comment by jordimas** [comment]
My current hypothesis is there is a problem with CTranslate2 and GPU on Windows due to CUDA or CTranslate2. 

In order to validate or invalidate this hypothesis I will ask you if you can try to run this simple code:

https://github.com/jordimas/calaix-de-sastre/blob/master/faster-whisper/inference.py

And tell me if you can reproduce the problem with this simple code. Thanks

**Comment by rsmith02ct** [comment]
I think there is some issue. After installing CUDA 12, CUDA 11, CUDNN, adding things to path, etc. still no luck with ctranslate2 and CUDA.

How can I execute the code?

**Comment by jordimas** [comment]
Sure

1. Download https://github.com/jordimas/calaix-de-sastre/blob/master/faster-whisper/inference.py
2. Run it with "python inference.py

**Comment by rsmith02ct** [comment]
Is this right?

C:\Users\rsmit>python inference.py
  File "C:\Users\rsmit\inference.py", line 72
    <title>calaix-de-sastre/inference.py at master ·
jordimas/calaix-de-sastre</title>
                                                   ^
SyntaxError: invalid character '·' (U+00B7)

C:\Users\rsmit>

**Comment by jordimas** [comment]
Look inside the file inference.py (open it with notepad), it looks like you download the HTML instead of the file.

**Comment by rsmith02ct** [comment]
That makes sense. I opened with notepad and pasted in the code, downloaded the mp3 here and changed the name to file.mp3.

![image](https://user-images.githubusercontent.com/122251109/233587286-156e8f36-ac2d-44cb-92eb-f24329ac75fb.png)

**Comment by jordimas** [comment]
Yes, you need to have in the same directory the file "file.mp3" which is giving you problems. (the file that I have there is for testing proposes).

The goal here is to see if you can reproduce the same problem observed in whisper-ctranslate2 with this simple version. Thanks

**Comment by rsmith02ct** [comment]
Thanks for being patient with me. Haven't really used a CLI since the days of Windows 95 or programmed anything since Pascal.

I edited the py from file.mp3 to file.mp4 and added a file I had used for testing before. It transcribed 65s of a 2min 35s file. I ran it on a Japanese video and it also worked very quickly and accurately for ~60s.

**Comment by rsmith02ct** [comment]
I see a big spike in GPU 3D activity so CUDA appears to be working.

**Comment by jordimas** [comment]
Version 0.2.6 should fix this.

**Comment by rsmith02ct** [comment]
Thank you for the update- it seems to be 0.2.7 and now works with CUDA. (though it is now case-specific for cpu and cuda and doesn't want uppercase anymore).
