### ISSUE TITLE
Add support for max_line_length and max_line_count

### ISSUE THREAD

**Issue by mayeaux** [Softcatala/whisper-ctranslate2#24]
As requested here: https://github.com/guillaumekln/faster-whisper/issues/156

Would be nice if we could get this implemented in `whisper-ctranslate2`

Relevant Whisper code:
https://github.com/openai/whisper/commit/43940fc9780cb91c4f94899755b4648e19d7b977

**Comment by jordimas** [comment]
I have implemented the same that OpenAI. It's not perfect but it's definitely useful for our use cases. Thanks
