### ISSUE TITLE
Please make sure libcudnn_ops_infer.so.8 is in your library path?

### ISSUE THREAD

**Issue by silvacarl2** [Softcatala/whisper-ctranslate2#27]
I keep getting this error no matter what I do:

Run on GPU with float16
Estimating duration from bitrate, this may be inaccurate
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Please make sure libcudnn_ops_infer.so.8 is in your library path!
Aborted (core dumped)

find / -name "libcudnn_ops_infer.so.8"
/home/silvacarl/.local/lib/python3.8/site-packages/nvidia/cudnn/lib/libcudnn_ops_infer.so.8

any ideas?

PATH=$(echo "$PATH:/usr/local/cuda-11.7/bin:/usr/lib/x86_64-linux-gnu:/home/silvacarl/.local/lib/python3.8/site-packages/nvidia/cudnn/lib")
LD_LIBRARY_PATH="/usr/local/cuda-11.7/lib64:/usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/home/silvacarl/.local/lib/python3.8/site-packages/nvidia/cudnn/lib"

even that doesnt work.

**Comment by silvacarl2** [comment]
i created a fresh ubuntu 20.04.

for some reason this is not getitng installed: libcudnn_ops_infer.so.8

which pip package does this come from?

**Comment by silvacarl2** [comment]
I apologize, i was testing this on WSL2.  on Ubuntu 20.04 in a VM, works great.

will check it on GPU next.

**Comment by silvacarl2** [comment]
ok, tried everything i can think of, this:

import time
from faster_whisper import WhisperModel
model_size = "large-v2"

print("Run on GPU with float16")
model = WhisperModel(model_size, device="cuda", compute_type="float16")
start_time = time.time()
segments, info = model.transcribe("12694263-Joan-Svarczkopf.mp3", beam_size=5)
print(info)
print("Detected language '%s' with probability %f" % (info.language, info.language_probability))
print("--- %s seconds ---" % (time.time() - start_time))
for segment in segments:
    print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))
print("--- %s seconds ---" % (time.time() - start_time))

gives me this error no matter what I do:

$ python faster-whisper-test.py 
Run on GPU with float16
Estimating duration from bitrate, this may be inaccurate
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Please make sure libcudnn_ops_infer.so.8 is in your library path!
Aborted (core dumped)

**Comment by silvacarl2** [comment]
$ whisper-ctranslate2 12694263-Joan-Svarczkopf.mp3 --compute_type int8_float16
Detecting language using up to the first 30 seconds. Use `--language` to specify the language
100%|████████████████████████████████████████| 922M/922M [00:03<00:00, 273MiB/s]
100%|█████████████████████████████████████| 2.29k/2.29k [00:00<00:00, 13.3MiB/s]
100%|███████████████████████████████████████| 449k/449k [00:00<00:00, 2.69MiB/s]
100%|█████████████████████████████████████| 2.10M/2.10M [00:00<00:00, 9.16MiB/s]
Estimating duration from bitrate, this may be inaccurate
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Please make sure libcudnn_ops_infer.so.8 is in your library path!
Aborted (core dumped)

**Comment by Botoni** [comment]
The same happened to me using an Anaconda virtual environment, this is the solution I found:

```
mkdir -p $CONDA_PREFIX/etc/conda/activate.d

echo 'CUDNN_PATH=$(dirname $(python3 -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)"))' >> $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh

echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/:$CUDNN_PATH/lib' >> $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh

source $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh
```

**Comment by kanazei** [comment]
I had this error in runpod.io. The following helped:
```
!apt-get install libcudnn8
!apt-get install libcublas-12-0 -y
```

**Comment by silvacarl2** [comment]
this nailed it for me:

export LD_LIBRARY_PATH=$(echo "$LD_LIBRARY_PATH:/usr/local/cuda-11.7/targets/x86_64-linux/lib/:/home/silvacarl/.local/lib/python3.8/site-packages/nvidia/cudnn/lib/")

**Comment by YusufCandraArif** [comment]
@silvacarl2 you save my day, thank you

**Comment by silvacarl2** [comment]
any time, ctranslate2 is awesome
