### ISSUE TITLE
compress json filesize

### ISSUE THREAD

**Issue by ras0k** [Softcatala/whisper-ctranslate2#31]
It seems the precision in the "accuracy" parameter is quite high, could we reduce to say 2 or even 1 significant digits if we want to save some memory space in the .json ? it seems right now a lot of tokens are consumed by this *extremely precise* parameter... maybe it could be an argument that states the precision (int 1 to 10)?

**Comment by jordimas** [comment]
There are two reasons for this:
- This is that OpenAI Whisper does, then we want to be as close as possible to the original behaviour
- You can always postprocess and remove data but not the way around 

Thanks for the suggestion anyway

**Comment by ras0k** [comment]
well said, thank you !

**Comment by ras0k** [comment]
what is your argument against my argument argument ? why would you ignore my argument argument by argumenting against my arugment argument ?

**Comment by ras0k** [comment]
for example, with your color-coding you bring it down to 0-255 which is a lot of precision lost, no ?
