### ISSUE TITLE
Live transcription is extremely inaccurate

### ISSUE THREAD

**Issue by coder543** [Softcatala/whisper-ctranslate2#33]
I'm not sure if I'm doing something wrong, but the live transcription feature is coming up with very strange transcriptions, even using a big model like `medium.en`. I'm speaking clearly into a nice microphone, and I have tested with another recording app that the microphone is working correctly.

"This is a test of the microphone" somehow transcribed to... "This is a stomacher from Eastern Siberia"!?

The transcription models work great if I record into an audio file and then pass that to `whisper-ctranslate2`, so it's just something weird going on with the live transcribe feature.

I'm on Windows 11, and I'm running this natively on Windows. (using the CPU since GPU transcription doesn't work for me on Windows at the moment, but it works fine in WSL2... but WSL2 doesn't have access to microphones.) So, it could be something weird with the mic API on Windows.

**Comment by coder543** [comment]
I also notice the live transcribe feature seems to wait for a large chunk of audio to accumulate, rather than attempting to transcribe in real time, which is unfortunate, and it uses a `live_volume_threshold` instead of the Silero VAD, I think?

I have been meaning to experiment with writing a real time Whisper transcription program, but I haven't found the time yet. I've been imagining that it would basically use a rolling last-30-seconds window, which is continuously fed into Whisper to refine the transcription. Somehow, as words are moving towards the front of the window and about to be removed, they would be saved as the correct transcription. Models like Whisper do better with more verbal context, instead of trying to transcribe a word just by itself. If the VAD detects a silence longer than a few seconds, it might make sense to just take whatever transcription we have and assume that is the end of that segment, then reset to a clean 30 second buffer if the user starts speaking again.

All of this is similar to how it _seems_ like Apple and Google do transcriptions when you're using their keyboards on a smartphone. You are continuously presented with a rough approximation of what you said, and it will attempt to refine words that have already been transcribed as you keep speaking.

I understand if the live transcription isn't a focus of this particular project, it's just something I'm interested in.

**Comment by jordimas** [comment]
Hello. 
My current assumption is that this is a Windows specific problem since the transcription works well in macOS and Linux. If you have other boxes handy, it will be great if you can test it in non-Windows OS. Thanks

**Comment by Hotohori** [comment]
Same problem here under Win10 with GPU transcription. It transcribes completely nonsense. I say "Hello" and it is turned into "Kiss"... Makes no sense at all.

I need it under windows. No option to test it under MacOS or Linux.

**Comment by TehVenomm** [comment]
I can echo this issue. Live transcription (GPU / CUDA) is extremely innacurate, however pre-recorded stuff is amazing however.

**Comment by mustafa0x** [comment]
Occurred with me on macos

**Comment by Purfview** [comment]
Same for me on Windows 7.

**Comment by jordimas** [comment]
Hi everybody. The functionality was developed in Linux and test also in mac OS. Works reasonable well in both operating systems. I do not have a Windows machine then I never tested in Windows.

This is an open source project, pull requests to address the problem in Windows are welcomed.

**Comment by mikaelhg** [comment]
One angle of attack for figuring this out would be to initialize the live transcription code path in a unit test, and feed it known-good data from a sound file. If that works, but sound capture doesn't, you know that the issue is in how sound capture is initialized and used on Windows.

**Comment by mpuz** [comment]
> Hi everybody. The functionality was developed in Linux and test also in mac OS. Works reasonable well in both operating systems. I do not have a Windows machine then I never tested in Windows.
> 
> This is an open source project, pull requests to address the problem in Windows are welcomed.

I have tested on ubuntu and results are unusable in live mode, while in file mode are perfect

**Comment by jordimas** [comment]
Pull requests are welcomed.
