### ISSUE TITLE
Extending CLI for Fine-Tuned Whisper Models on Hugging Face

### ISSUE THREAD

**Issue by anilbey** [Softcatala/whisper-ctranslate2#34]
Hi,

In addition to the standard models such as tiny, base, small, medium, and large, the community has also created fine-tuned models like the one found at https://huggingface.co/sefa-alper/whisper-turkish-large-v2.

Could you please provide guidance on how we can incorporate these fine-tuned Whisper models into the CLI for seamless integration and use? 

Thank you in advance.

**Comment by jordimas** [comment]
Hello. This is explained here: https://github.com/Softcatala/whisper-ctranslate2/blob/main/README.md

If it's not clear, let me know and I will improve the documentation. Thanks

**Comment by Alistair1231** [comment]
I use this powershell script to get the models to the ct2 format
```ps1
$modelPath = "D:/Programs/WhisperDesktop" #no trailing slash
# https://huggingface.co/bofenghuang/whisper-large-v2-cv11-german
$modelAuthor = "vumichien"
$modelName = "whisper-large-v2-cv11-german"

Write-Output @"
from transformers import AutoProcessor, AutoModelForSpeechSeq2Seq, AutoTokenizer

# load model
processor = AutoProcessor.from_pretrained("$modelAuthor/$modelName")
model = AutoModelForSpeechSeq2Seq.from_pretrained("$modelAuthor/$modelName")
tokenizer = AutoTokenizer.from_pretrained("$modelAuthor/$modelName")

# save model with tokenizer.json
processor.save_pretrained("$modelPath/$modelName")
model.save_pretrained("$modelPath/$modelName")
tokenizer.save_pretrained("$modelPath/$modelName")
"@ | python

# replace / with \ in path
$modelPath = $modelPath.Replace('/', '\')
# convert to ct2
Invoke-Expression "ct2-transformers-converter --model '$modelPath\$modelName' --output_dir '$modelPath\ct2-$modelName' --quantization float16 --copy_files tokenizer.json"
```
Afterwards you can use it by adding
`--model_directory 'D:\Programs\WhisperDesktop\ct2-whisper-large-v2-cv11-german'`
Do not add `--model` !

Sadly right now I also don't get any output files generated on Windows, but the approach would be the same on linux.

**Comment by jordimas** [comment]
CTranslate2 provides ct2-transformers-converter (https://opennmt.net/CTranslate2/guides/transformers.html) which provides a cli to convert fine-tunned models. I recommend this using this tool.

**Comment by anilbey** [comment]
Ah yes it works. The information provided on the README was sufficient. Thanks @jordimas  and @Alistair1231  .
