### ISSUE TITLE
Please support python API for whisper-ctranslate2

### ISSUE THREAD

**Issue by wjc1989** [Softcatala/whisper-ctranslate2#36]
I want to integrate whisper-ctranslate2 to my system, can you support API for whisper-ctranslate2, I use Python coding, thanks very much.

**Comment by jordimas** [comment]
You can use the [Faster-whisper](https://github.com/guillaumekln/faster-whisper) API. You can see how whisper-ctranslate2 actually uses it since its a client to this API.

**Comment by wjc1989** [comment]
> 

I test faster-whisper, every time return different result, and the accuracy not better.
If I set temperqture=0, the result is very bad
I  do not know why.

**Comment by jordimas** [comment]
Whisper-ctranslate2 uses faster-whisper. You should get the same results. If you are using the API directly, feel free to open an issue in https://github.com/guillaumekln/faster-whisper/issues
