### ISSUE TITLE
Consider adding options list to readme

### ISSUE THREAD

**Issue by thibaultmol** [Softcatala/whisper-ctranslate2#38]
Similar to how whisper.cpp has listed in it's quick start. A nice overview of all the options (I know you can just run the command and it'll output them in the terminal as well. But it would nice if it was documented in the readme as well)

https://github.com/ggerganov/whisper.cpp#quick-start

**Comment by jordimas** [comment]
Hi. There is a  "Usage" section in https://github.com/Softcatala/whisper-ctranslate2 which covers this.

**Comment by thibaultmol** [comment]
Which just points to using the cli to get the options list. I just wanted
to suggest that maybe the list could also be in the readme itself
