### ISSUE TITLE
diarize option?

### ISSUE THREAD

**Issue by thibaultmol** [Softcatala/whisper-ctranslate2#39]
it seems like diarize is possible with faster whisper, but whisper-ctranslate2 doesn't support the argument?
 [whisper-diarize](https://github.com/MahmoudAshraf97/whisper-diarization)

**Comment by sicora-pixel** [comment]
Have you found anything about it?

**Comment by jordimas** [comment]
Diarization experimental support has been added in version 0.36 released today in case you want to give it a try.
