### ISSUE TITLE
Using GPU without any output

### ISSUE THREAD

**Issue by despairTK** [Softcatala/whisper-ctranslate2#40]
![1](https://github.com/Softcatala/whisper-ctranslate2/assets/111871110/325b98ef-e537-4446-859d-3f913ee00eb5)
![2](https://github.com/Softcatala/whisper-ctranslate2/assets/111871110/f0d45100-3a38-4f51-a4ba-78ec7904eb4e)

These two screenshots are that I use CPU and GPU to transcribe the same audio, and it can be found that the CPU can run normally, but the GPU has no output. My OS is windows 11.

**Comment by rsmith02ct** [comment]
Same as here likely: https://github.com/Softcatala/whisper-ctranslate2/issues/29

**Comment by despairTK** [comment]
> Same as here likely: #29

Is there no workaround now?

**Comment by rsmith02ct** [comment]
I haven't found a way to get it to work myself (even after installing DNN, CUDA, etc.) 
There's another implementation here which doesn't rely on the buggy CLI and works for me: https://github.com/Purfview/whisper-standalone-win/releases

**Comment by jordimas** [comment]
Version 0.2.6 should fix this.
