### ISSUE TITLE
I get error code 126 with CUDA installed and running. 

### ISSUE THREAD

**Issue by francofang** [Softcatala/whisper-ctranslate2#41]
I get this error message:

Could not load library cudnn_cnn_infer64_8.dll. Error code 126
Please make sure cudnn_cnn_infer64_8.dll is in your library path!

I double check my Windows 10 Environment Variables， and cudnn_cnn_infer64_8.dll directory is there.

Anything I do wrong?

**Comment by Zacharie-Jacob** [comment]
https://github.com/Softcatala/whisper-ctranslate2/issues/27

This has been a persistent problem for Windows users.  I was never able to get it working without making a bunch of copies of the .dll files.  Unfortunately I forgot which directory solved my problem (which I am having again after a fresh install of anaconda)

**Comment by rsmith02ct** [comment]
Is it in C:\Program Files\NVIDIA\CUDNN\v8.x\lib\x64? with the v8.x saved in path? Seems to work here.

**Comment by francofang** [comment]
Hi all

Finally got it working.

IT is because cudnn needed zlib to work.

 I did not install [zlib](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-zlib-windows), and after I install it, it worked.

Make sure you read install guide.

**Comment by tiennguyen12g** [comment]
If anyone get this error, it means somethings wrong when use GPU to run command. So , you can use CPU instead by added `--device cpu` it will run whisper on CPU
