### ISSUE TITLE
Is possible to support with ydotool / nerd-dictation in whisper-ctranslate2 ?

### ISSUE THREAD

**Issue by grigio** [Softcatala/whisper-ctranslate2#43]
I tried 

```
whisper-ctranslate2 --live_transcribe True  --model small
```

and live mode works fine, but i'd like to get the output in a non-interactive way, is possible to receive the output of the spoken text after N seconds of silence ?

**Comment by jordimas** [comment]
You can play with these variables:

https://github.com/Softcatala/whisper-ctranslate2/blob/main/src/whisper_ctranslate2/live.py#L10

These are not available in the cmd, then you need to change the code locally.
