### ISSUE TITLE
Help, the software is not working!

### ISSUE THREAD

**Issue by boykan313** [Softcatala/whisper-ctranslate2#45]
![1](https://github.com/Softcatala/whisper-ctranslate2/assets/90963133/e89afd56-e56d-4aed-822c-21ee4b25e7cd)
![2](https://github.com/Softcatala/whisper-ctranslate2/assets/90963133/5603b308-95dd-4456-8bca-a27a907fa974)
Hello! I installed the usual whisper, and then yours, after installing CTranslate2. Your software doesn't want to work even when set to medium, the usual whistle works on large-v2. Please help, I really need this software! On the first screen, I tried to use two commands. One so that he himself would determine the language, the second he independently indicated. In the case when he himself determines the language, nothing happens, and when I prompt him, the line is instantly reset to a new one without results. For comparison, I entered the same commands through the usual whisper, where everything works, even the large-v2 mode, it just takes a lot of time.

**Comment by jordimas** [comment]
Which version of whisper-ctranslate2 are you using?
Are you using CPU or GPU?

**Comment by boykan313** [comment]
> Какую версию шепота-ctranslate2 вы используете? Вы используете процессор или графический процессор?

I am using the latest version of your software and I am using a GPU. cuda and the rest of the software is installed, except for NVIDIA cuBLAS, at the moment it does not have support on windows, but this does not prevent me from using gpu on a regular visper, which confirms my screen.

**Comment by jordimas** [comment]
I do not own a Windows box. I cannot help you with Windows specific issues.

What I can say is make sure that you are running whisper-ctranslate 0.26 which was release today, since it contains a Windows fix.

**Comment by boykan313** [comment]
> I do not own a Windows box. I cannot help you with Windows specific issues.
> 
> What I can say is make sure that you are running whisper-ctranslate 0.26 which was release today, since it contains a Windows fix.


does the new version need to be installed in some special way or is it enough to type the command "pip install -U whisper-ctranslate2"?

**Comment by boykan313** [comment]
> I do not own a Windows box. I cannot help you with Windows specific issues.
> 
> What I can say is make sure that you are running whisper-ctranslate 0.26 which was release today, since it contains a Windows fix.

tell me how can I make sure that this version works for me, if nothing happens after piercing this command. For example, having broken through the whisper command, there is a reaction.
![3](https://github.com/Softcatala/whisper-ctranslate2/assets/90963133/5355761d-67d8-477d-adaf-5b75da0098cc)
Thank you for your reply, I really want to understand this topic.

**Comment by jordimas** [comment]
Try

 _whisper-ctranslate2 --version_

it should show:

_whisper-ctranslate2 0.2.6_

If it's older, try:

_pip3 install whisper-ctranslate2==0.2.6_

**Comment by boykan313** [comment]
![45](https://github.com/Softcatala/whisper-ctranslate2/assets/90963133/4e37b81a-bb04-4bf7-a540-ab5be8198bf2)
Version 0.2.6 is installed, but still nothing happens after the main command is executed, it hangs on the language detection.

**Comment by jjj001** [comment]
I have similar problem.

I tried to process mp3 file, it downloaded model, detected language and after a short while finished without any error message nor output file. It does even with very short mp3 file and tiny database.

**Comment by yslion** [comment]
same issue   on Win10   , also sucks without anything outputing .   check your Python version   .   It works for me when I change  3.9 .x  to 3.10.6

**Comment by koenigscode** [comment]
a uni colleague had the same problem (windows), he has an NVIDIA gpu in his laptop (surface laptop studio), and it defaulted to cuda, but same as here it just stuck at detecting the language. 
explicitly setting --device cpu worked (huge performance loss i suppose, but hey, at least it runs)

used version 0.2.9

so I guess this issue is similar to #40
