### ISSUE TITLE
Random stops

### ISSUE THREAD

**Issue by goodenn** [Softcatala/whisper-ctranslate2#46]
@jordimas 
Thanks for your effort to offer this great tool.
I've enjoyed it many times with diffferent audios and videos.

However, I've also encountered several stops, that the transcripting will stopped randomly at different localtions of a video, when I tried the 2nd or 3rd time by ending the 1st task, then it'll finish the transcripting that audio or video.
I'm using the Intel NUC11 with modified cooling fan (No GPU but will better cooling for CPU).
What's the possible reason and how to tackle it? Could you plz share your thoughts?
Thanks!

**Comment by jordimas** [comment]
Hello. When Whisper get lots it uses random heuristics based on temperature.

Try to use the parameter "--temperature_increment_on_fallback None" to see if makes any difference.

**Comment by goodenn** [comment]
Thanks for your comments.

I've already been using this parameter, it still stops sometimes, especially when Windows gets into the sleep mode.
Below is the full command I'm using in Total Commander (a windows file manager):
"whisper-ctranslate2 %P%S --model medium --temperature_increment_on_fallback None --language en --compute_type int8 --vad_filter True --output_format srt  --output_dir %P"

Now I'm trying a small App called "Don't sleep" which will prevent the computer from going to sleep by monitor the CPU usage constantly. 
(If CPU usage is higher than the setting value, it'll keep the windows awake)
