### ISSUE TITLE
initial_prompt?

### ISSUE THREAD

**Issue by silvacarl2** [Softcatala/whisper-ctranslate2#47]
can you add initial_prompt to this?  it is really helpful in a lot of situations:

whisper-ctranslate2 --model large-v2 --compute_type int8 --output_format json --vad_filter True --language en --word_timestamps True --initial_prompt "Joan Svarczkopf" 12694263-Joan-Svarczkopf.mp3

**Comment by jordimas** [comment]
Hello, 

Initial prompt is already supported:

<img width="609" alt="Captura de pantalla 2023-06-13 a les 7 24 13" src="https://github.com/Softcatala/whisper-ctranslate2/assets/309265/fffd8e4f-996a-4755-96eb-92122238566c">

Have you observed any problem with it?

Thanks,

Jordi

**Comment by silvacarl2** [comment]
i totally apologize, got it thx!  this tool is awesome!!
