### ISSUE TITLE
can Whisper run on the gaps between each speech section？

### ISSUE THREAD

**Issue by zx3777** [Softcatala/whisper-ctranslate2#49]
Could you add an option? Sometimes using vad will miss dialogue，and --vad_threshold VALUE (float) is useless.

Like this：

* silero-vad
 
 * Use Silero VAD to detect sections that contain speech, and run Whisper on independently on each section. Whisper is also run on the gaps between each speech section, by either expanding the section up to the max merge size, or running Whisper independently on the non-speech section.

* silero-vad-expand-into-gaps

  * Use Silero VAD to detect sections that contain speech, and run Whisper on independently on each section. Each spech section will be expanded such that they cover any adjacent non-speech sections. For instance, if an audio file of one minute contains the speech sections 00:00 - 00:10 (A) and 00:30 - 00:40 (B), the first section (A) will be expanded to 00:00 - 00:30, and (B) will be expanded to 00:30 - 00:60.

**Comment by jordimas** [comment]
This is already done. If you're missing any VAD option please open a new ticket.
