### ISSUE TITLE
How to transfer the word-level timestamped json to srt? 

### ISSUE THREAD

**Issue by lj739** [Softcatala/whisper-ctranslate2#50]
How to transfer the word-level timestamped json to srt?

**Comment by jordimas** [comment]
If you use --word_timestamps, the srt will follow the word level timestamps and show it in the subtitles accordingly.

**Comment by lj739** [comment]
I do used  --word_timestamps, what I got is a srt file and a json file, the srt file just had timestamp on sentence, the json file had word timestamp but i don't know how to use this file.

**Comment by lj739** [comment]
I didn't use --highlight words, no word time code in the srt file, a json file created instead.

**Comment by jordimas** [comment]
SRT is a subtitle format. See: https://docs.fileformat.com/video/srt/

The goal of the SRT format is to provide subtitles to videos while JSON is to share information with applications.

The --word_timestamps impact of in STR is that the time stamps are more precise. If you need the data, use the JSON.

Behaviour is the same than the original OpenAI client.

If you have a problem regarding this tool, feel free to open a bug report. Thanks
