### ISSUE TITLE
--live_transcribe does nothing for me in macOS

### ISSUE THREAD

**Issue by adriangalilea** [Softcatala/whisper-ctranslate2#51]
I did double-check terminal permissions and indeed it has microphone permission.

```
(base) ➜  ~ whisper-ctranslate2 --live_transcribe True --language es
Live stream device: Mac mini Speakers
Listening.. (Ctrl+C to Quit)
```

It sais listening and that's about it, also I noticed that it didn't even get into this stage when I first installed and launched it directly, I had to first transcribe a .wav file.

**Comment by adriangalilea** [comment]
Woops.

Since I noticed that I tried:

Uninstalling
Installing
Running a regular command with a file and specifying model.
Then trying live_transcription and it worked.

So it's fine, just so you know there's a bug there.

**Comment by mustafa0x** [comment]
Same occurred to me

**Comment by KayLeung** [comment]
i have no output also. I've downloaded the model and tried re-install again.

**Comment by sb1992** [comment]
Same problem .. it just shows listening and nothing happens. am using m2 mac

**Comment by jordimas** [comment]
@sb1992 This may help: https://github.com/Softcatala/whisper-ctranslate2/blob/main/FAQ.md#live-transcription-does-not-work

**Comment by sb1992** [comment]
Thank you changing the value of live volume threshold did the trick. Much appreciated
