### ISSUE TITLE
2 hour video but generated transcription of only 35 mins.

### ISSUE THREAD

**Issue by deadcoder0904** [Softcatala/whisper-ctranslate2#53]
i had used this command:

```bash
whisper-ctranslate2 video.mp4 --model medium.en --output_format srt > x.srt
```

and it stopped midway.

the transcription also started long like 1 sentence & then gave word-level timestamps. this was probably bcz i was simultaneously using macwhisper. but i stopped later on.

is that bcz my terminal can't hold that much output?

i would also love to see progress % like i can see in macwhisper.

and an export option would be cool rather than using `> x.srt`... idk if it'll not stop then.

anyways, what do you think is this case?

**Comment by deadcoder0904** [comment]
alright, i tried it again & this time it worked. took 4 hours 25 mins lol for a 2 hour video.

however, the transcriptions are in a weird format that they don't open.

i can't attach `.srt` files here so i'll just paste them. one that `whisper-ctranslate2` generated will be named `x.srt` which doesn't work properly & another one is `y.srt` that loads in vlc properly.

### x.srt

```srt
Detected language 'English' with probability 1.000000
[00:00.940 --> 00:04.620]  Alright, boom, let's get it going. We only got two hours we want to get through this
[00:04.620 --> 00:10.060]  whole thing. Welcome, everyone a couple quick logistics just to talk frequently asked questions
[00:10.060 --> 00:14.360]  before we dive in, you will have lifetime access to this recording, we will distribute
.
.
.
[01:58:43.740 --> 01:58:44.580]  Take it easy. Y'all.
Transcription results written to '/Users/deadcoder0904/Downloads' directory
```

`x.srt` doesn't load properly for some reason.

### y.srt

```srt
1
0:00:00.000 --> 0:00:05.120
All right, boom, let's get it going. We only got two hours. We want to get through this whole thing.

2
0:00:05.640 --> 0:00:11.000
Welcome everyone. A couple quick logistics just to talk frequently asked questions before we dive in.

3
0:00:11.280 --> 0:00:15.840
You will have lifetime access to this recording. We will distribute it immediately afterwards.
.
.
.

876
1:58:41.480 --> 1:58:45.480
event. Have a great weekend. Take it easy, y'all.
```

`y.srt` loads in vlc properly.

now i can do the formatting in python or chatgpt but i would love to have it generate `.srt` files easily like `y.srt` so it plays properly. maybe there is a universal subtitle format idk.

**Comment by deadcoder0904** [comment]
so i tried a bunch of python scripts but couldn't find a way to convert timing easily. might have to write some algo for that.

```python
import fileinput

output = ''
line_number = 1
for line in fileinput.input('subtitle.srt', inplace=True):
	output += "{}\n{}".format(line_number, line).replace("[", "").replace(
	 "]  ", "\n") + "\n"
	line_number += 1

with open(r'subtitle.srt', 'w') as file:
	file.write(output)
```

but this thing works → https://gotranscript.com/subtitle-converter

my subtitles finally load in vlc with this. i think it'd be good if the `.srt` files generated look like the ones generated from above site.

**Comment by phineas-pta** [comment]
> an export option would be cool rather than using `> x.srt`

did u see this message

`Transcription results written to '/Users/deadcoder0904/Downloads' directory`

> took 4 hours 25 mins lol for a 2 hour video

need pc with gpu or mac apple silicon for better speed

**Comment by jordimas** [comment]
> and an export option would be cool rather than using `> x.srt`... idk if it'll not stop then.

By default whisper-ctranslate will produce files with all formats in the target directory:

_Transcription results written to '/Users/deadcoder0904/Downloads' directory_

The have the same filename that the original audio/video file but with the srt, json and other extensions.

The output of the tool it's to understand progress and if you redirect it > to a file is not any specific file format, it's just the tool output.

**Comment by deadcoder0904** [comment]
> Transcription results written to '/Users/deadcoder0904/Downloads' directory

yes, i did @phineas-pta 

> The output of the tool it's to understand progress and if you redirect it > to a file is not any specific file format, it's just the tool output.

@jordimas is there a way so that the output generates a `.srt` file? bcz that's what i wanted it for. not sure if its the use-case you built it for?

**Comment by deadcoder0904** [comment]
oh yes, it works.

i thought it prints only on cli but never checked it.

the new command became:

```bash
whisper-ctranslate2 x.mp4 --model medium.en --language en --output_format srt --word_timestamps true
```

i do think you should put this in the readme.
