### ISSUE TITLE
0.2.9 --help explained incorrectly

### ISSUE THREAD

**Issue by zx3777** [Softcatala/whisper-ctranslate2#56]
--repetition_penalty REPETITION_PENALTY
                        prevent repetitions of ngrams with this size (set 0 to disable) (default: 1.0)
--no_repeat_ngram_size NO_REPEAT_NGRAM_SIZE
                        Penalty applied to the score of previously generated tokens (set > 1 to penalize) (default: 0)

The explanations of these two items are reversed, but "default" is correct.

**Comment by jordimas** [comment]
Fixed, thanks for reporting
