### ISSUE TITLE
Additional quants please!

### ISSUE THREAD

**Issue by BBC-Esq** [Softcatala/whisper-ctranslate2#59]
Love your program.  However, I was wondering if the other quants could be included as well that are on the ctranslate2 docs; specifically, int8_float32, int8_float16, int8_bfloat16?  I believe that's all of them, but doublecheck here:

[https://opennmt.net/CTranslate2/quantization.html](url)

Almost forgot!  Please also include bfloat16 if you can!

**Comment by jordimas** [comment]
Thanks for reporting this. The new types have been added recently. 
Version 0.31 will include new ones

**Comment by BBC-Esq** [comment]
Thanks....Is it possible to use this command instead if I don't want to wait for the official release?  pip install git+https://github.com/jordimas/whisper-ctranslate2.git

**Comment by jordimas** [comment]
I released a version this morning, doing this should give you the last version:

`pip3 install whisper-ctranslate2==0.3.1`

**Comment by BBC-Esq** [comment]
I ran the command above that I mentioned and it installed version .3.2...Is this OK or do you think that there might be something unstable?

**Comment by BBC-Esq** [comment]
It states: `whisper-ctranslate2 0.3.2`

**Comment by jordimas** [comment]
No, at the moment 0.3.1=0.3.2 since I just bump the version

**Comment by BBC-Esq** [comment]
Got it, thanks!
