### ISSUE TITLE
Ablility to specify model directory

### ISSUE THREAD

**Issue by BBC-Esq** [Softcatala/whisper-ctranslate2#60]
I've converted a Whisper model to ctranslate2 format and am trying to set the path to it with the --model_dir but it keeps downloading the model from huggingface instead?  It then saves the model I downloaded in the model directory I tried to set...Apparently, --model_directory is only for specifying where to save the model...not where the model files are located to use.  Is there a way to specify the directory where the model files to use are?  I want to convert the float32 model (original whisper) to int8_float32 ctranslate2 format, and don't want to rely on the ctranslate2 models that whisper-ctranslate2 downloads.  They are all encoded with the float16 type, which was done before ctranslate2 added int8_float32 support I think...and bfloat etc.

**Comment by jordimas** [comment]
If you want to load a finetuned model use --model_directory like in this example:

_whisper-ctranslate2 inaguracio2011.mp3 --model_directory /home/jordi/sc/whisper/whisper-tools/openai-whisper-medium2_

This should work.
