### ISSUE TITLE
Support Whisper large-v3?

### ISSUE THREAD

**Issue by gary109** [Softcatala/whisper-ctranslate2#67]

**Comment by slavonnet** [comment]
https://github.com/guillaumekln/faster-whisper/pull/549

**Comment by silvacarl2** [comment]
will large-v3 and distaill-whisper be added?

Model selection options:
  --model {tiny,tiny.en,base,base.en,small,small.en,medium,medium.en,large-v1,large-v2}
                        name of the Whisper model to use (default: small)

**Comment by timreuscher** [comment]
> will large-v3 and distaill-whisper be added?
> 
> Model selection options: --model {tiny,tiny.en,base,base.en,small,small.en,medium,medium.en,large-v1,large-v2} name of the Whisper model to use (default: small)

CTranslate2 just added support for both (see https://github.com/OpenNMT/CTranslate2/releases/tag/v3.21.0), so things look good.

**Comment by jordimas** [comment]
Yes, version 0.33 has added support for it.

**Comment by silvacarl2** [comment]
awesome!  any plans for distil-whisper?

**Comment by jordimas** [comment]
For distil, support was added yesterday in version 0.41
