### ISSUE TITLE
distill-whisper?

### ISSUE THREAD

**Issue by silvacarl2** [Softcatala/whisper-ctranslate2#68]
you you be able to add support for distill-whisper?

**Comment by Purfview** [comment]
faster-whisper is like "distill-whisper", except that it's much better. 😆

**Comment by silvacarl2** [comment]
agreed but still would like to test/benchmark it.

**Comment by Purfview** [comment]
There is PR at the reference faster-whisper repo.

**Comment by jordimas** [comment]
Thanks, this has been released.
