### ISSUE TITLE
Save/record the audio into files

### ISSUE THREAD

**Issue by aindilis** [Softcatala/whisper-ctranslate2#79]
Hi,

First, this is an enormously useful system. Thank you for making it.

Second, I was wondering if it were possible to save or record the original audio into files.

Some features that would be ideal would be:

+ using the VAD to avoid recording silence or non-speech audio
+ rotating audio recording files, such that once a size limit is reached, it overwrites itself
+ separate audio files, timestamped, with corresponding txt and vtt file
+ diarization, of course
+ probably many other features

Thanks!

**Comment by jordimas** [comment]
This will be out of scope of a this tool which is just a cli over faster-whisper2.
For this kind of tasks you can call directly https://github.com/SYSTRAN/faster-whisper and write your small client, it's just a few lines of code.
