### ISSUE TITLE
Can you please add support for word_timestamps, highlight_words and max_words_per_line?

### ISSUE THREAD

**Issue by FurkanGozukara** [Softcatala/whisper-ctranslate2#82]
I use these 3 with whisper

example command i tried

`cmd /c whisper-ctranslate2 "C:\temp\a\1.mp3" --model large-v1 --language en --initial_prompt "Welcome our Youtube channel." --best_of 10 --beam_size 10 --word_timestamps True --highlight_words True --max_words_per_line 8 --output_dir  "C:\temp\a"`

**Comment by jordimas** [comment]
This has been added in the version released to today 0.4.0. Thanks

**Comment by FurkanGozukara** [comment]
> This has been added in the version released to today 0.4.0. Thanks

awesome thank you
