### ISSUE TITLE
Problem running it on Windows 11

### ISSUE THREAD

**Issue by ochiana** [Softcatala/whisper-ctranslate2#84]
I have a problem running this in Windows and I don't know what's wrong. I installed it with pip in an venv. Apparently it works the same either the venv is activated or not. I tried it in all shells: Power Shell, Command Prompt, Cross Tools Command prompt for VS. The behaviour is the same.

I execute it like this: 

 .\venv\Scripts\whisper-ctranslate2.exe --model large-v2 --output_format all  --device cuda --device_index 1 --task transcribe --language ro audio.mp3
Detected language 'Romanian' with probability 1.000000

It loads the model in VRAM, the power usage of the selected GPU increases, then it outputs the line about detected language and then it stops, just like it finishes. But there's no output, no files.

I tried the same audio files on the original Whisper and on the Whisper binary standalone for Windows. Both work. Unfortunately none of them have the device_index implemented.

Any idea how can I force whisper-ctranslate2 to report the problem?

**Comment by Purfview** [comment]
> I tried the same audio files on the original Whisper and on the Whisper binary standalone for Windows. Both work. Unfortunately none of them have the device_index implemented.

Both have it: `--device cuda:1`

**Comment by leezer3** [comment]
The issue is that you're missing the CUDA neural network DLLs.

https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/windows-x86_64/

Download the version matching your CUDA runtime, and extract into (e.g.) **C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin**
