### ISSUE TITLE
--word_timestamps = True not working

### ISSUE THREAD

**Issue by ollisulopuisto** [Softcatala/whisper-ctranslate2#87]
Hi.

I think this might be user error (hopefully!), but when I run whisper-ctranslate2 inside Google Colab with the following command 

`!whisper-ctranslate2 "{full_path}" --vad_filter True --model large-v2 --verbose True --language fi --word_timestamps True --output_dir "{transcripts_dir}"`

I get perfectly nice sentence-level output in JSON and every other format, but no word-level tagging. I've tried removing some of the parameters, but haven't gotten it to work yet. Removing vad_filter doesn't seem to do anything. 

Is this a language-dependant thing (i.e. Finnish & large-v2) or is there something else I'm missing?

Both {full_path} and {transcripts_dir} contain meaningful values.

**Comment by jordimas** [comment]
Hello. 
It's not language or model dependant. It works for me.
Some ideas:
- Make sure that you use the whisper-ctranslate2 version 0.4.1 or higher
- Look in the JSON for  '"words": [' it should be there, even if is not added you should see a   "words": null
- Try it outside  Google Colab
