### ISSUE TITLE
Path to local model directory should be considered a valid model option

### ISSUE THREAD

**Issue by lutangar** [Softcatala/whisper-ctranslate2#92]
Considering `openai-whisper` is the reference implementation,  in `open-whisper` one may provide a path to a model instead of the name of a model.

Here's the`load_model` implementation :
```python
if name in _MODELS:
    checkpoint_file = _download(_MODELS[name], download_root, in_memory)
    alignment_heads = _ALIGNMENT_HEADS[name]
elif os.path.isfile(name):
    checkpoint_file = open(name, "rb").read() if in_memory else name
    alignment_heads = None
else:
    raise RuntimeError(
        f"Model {name} not found; available models = {available_models()}"
    )
```
> https://github.com/openai/whisper/blob/main/whisper/__init__.py#L132-L141

On the other hand, in `whisper-ctranslate2` the *same* feature is only achievable using yet another option `--model_directory`.
> *Which is  confusing btw since there is another option named `model_dir`...*

~~Furthermore, there is a hard constraint on the model filename which must be named `model.bin`. Anything else would be considered invalid.~~
> see https://github.com/Softcatala/whisper-ctranslate2/blob/main/src/whisper_ctranslate2/whisper_ctranslate2.py#L172

The `openai-whisper` whisper behavior could be implemented in `whisper-ctranslate2`  for :
- more flexibility
- better compatibility with the reference CLI

**Comment by lutangar** [comment]
I wrongly assumed a **CTranslate2** model could be a single `.bin` file as `openai-whisper` `--model` option may  point to a single `.pt` file. 

Still, I think this issue remains relevant, the `--model` option could be used to point to either a model name or model directory instead of relying on an extra `model_directory` option.

**Comment by jordimas** [comment]
Thanks for your feedback. No plans to change this at this point.
