### ISSUE TITLE
The Timeline of the command line is different from the Timeline of the output file?

### ISSUE THREAD

**Issue by zx3777** [Softcatala/whisper-ctranslate2#99]
windows10 
whisper-ctranslate2 0.4.4
faster whisper 1.0.2
cuda12 py310
--vad_filter false --word_timestamps True

command line                                             
[00:00.000 --> 00:02.380]  
[00:03.840 --> 00:04.000]  
[00:05.720 --> 00:06.000]  
[00:07.120 --> 00:08.000] 
[00:08.600 --> 00:10.100]  
[00:10.100 --> 00:12.000]  
[00:16.000 --> 00:17.600]  
[00:18.260 --> 00:20.000]  

output file .srt
1
00:00:00,000 --> 00:00:02,380
2
00:00:03,840 --> 00:00:04,540
3
00:00:05,720 --> 00:00:06,420
4
00:00:07,120 --> 00:00:08,000
5
00:00:08,600 --> 00:00:10,100
6
00:00:10,100 --> 00:00:12,000
7
00:00:16,000 --> 00:00:17,600
8
00:00:18,260 --> 00:00:20,200

Why does this happen?

**Comment by jordimas** [comment]
Hello. Can you share the file that allows me to reproduce this? Thanks

**Comment by zx3777** [comment]
> Hello. Can you share the file that allows me to reproduce this? Thanks
this file:

https://pixeldrain.com/u/98UrzQxp

my command: 
whisper-ctranslate2 --model medium --output_format srt --local_files_only True --word_timestamps True --language ko --vad_filter false test_30sec.aac
